version: '3.9'
services: 
    backend:
        container_name: flask
        build: 
            context: .
            dockerfile: Dockerfile
        command: python main.py
        ports: 
            - 8001:5000
        volumes: 
            - .:/app 
        dns: 
            - 8.8.8.8
            - 8.8.4.4
            - 192.168.0.29
        depends_on:
            - db

    queue: 
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'python consumer.py'
        depends_on: 
            - db
    
    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: main
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - .dbdata:/var/lib/mysql 
        ports:
            - 33067:3306
